### ISSUE TITLE
Unable to run the readme example

### ISSUE THREAD

**Issue by amititash** [kootenpv/spacy_api#2]
Hi, 

I am trying to run the example given in the readme. I have spacy installed and I am running python 2.7.10 on Mac OS. I am getting the following error 

`Traceback (most recent call last):
  File "test.py", line 3, in <module>
    spacy_client = Client() # default args host/port
  File "/Library/Python/2.7/site-packages/spacy_api/client.py", line 95, in __init__
    super(Client, self).__init__(model, embeddings_path)
TypeError: must be type, not classobj`

Is this due to my python version or something else ? Sorry, I am new to Python. Appreciate any pointers.  Thanks.

**Comment by NeuroWinter** [comment]
I also have this issue. Running Python2.7

**Comment by kootenpv** [comment]
Sorry guys, I have somehow missed this issue. I'll have a look at this later today.

**Comment by kootenpv** [comment]
Ok I couldn't help but look.... and it was an obvious mistake. The new version should work.

    pip install -U spacy_api
